const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createRequire}=require('node:module');
const project=path.join(__dirname,'..');
const {chromium}=createRequire(path.join(project,'smithstem/package.json'))('playwright-core');
const evidence=path.join(project,'evidence/flows/Management_Dashboard');
async function run(){
  fs.mkdirSync(evidence,{recursive:true});
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:960}});
  page.setDefaultTimeout(7000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  console.log('RUNTIME browser ready');
  await page.goto('http://127.0.0.1:4173/management-dashboard.html?screen=home&business=NorthQuest&v=3');
  const heading=name=>page.getByRole('heading',{name,exact:true}).waitFor({state:'visible'});
  const click=name=>page.getByRole('button',{name,exact:true}).click();
  const clickAmara=()=>page.getByRole('button',{name:/Amara Okafor/}).click();
  await click('Trial results');await heading('Trial results');console.log('RUNTIME trial queue ready');await clickAmara();await heading('Amara Okafor');
  assert.equal(await page.getByRole('img',{name:'Submitted TikTok screenshot showing 10,240 views',exact:true}).count(),1);
  await click('Open TikTok video');assert.match(await page.locator('#transition').innerText(),/exact TikTok post/);
  await click('Back');await heading('Trial results');
  await clickAmara();await click('Approve trial');await heading('Trial approved');
  assert.match(await page.locator('main').innerText(),/Nothing is completed until she signs and submits/);
  await click('Management home');await click('Onboarding submissions');await heading('Onboarding submissions');console.log('RUNTIME onboarding queue ready');await clickAmara();await heading('Amara Okafor');
  for(const value of ['0123456789','Signature validation passed','Review signed agreement'])assert.match(await page.locator('main').innerText(),new RegExp(value));
  console.log('RUNTIME onboarding review ready');await page.screenshot({path:path.join(evidence,'revision3-onboarding-desktop.png'),fullPage:true});
  await click('Complete onboarding');await heading('Onboarding completed');assert.match(await page.locator('main').innerText(),/Amara is now active in NorthQuest/);
  await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4173/management-dashboard.html?screen=home&business=NorthQuest&v=3');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'phone layout has no horizontal overflow');
  await click('Trial results');await clickAmara();await page.screenshot({path:path.join(evidence,'revision3-trial-evidence-phone.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'phone evidence has no horizontal overflow');
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS trial result routes to evidence and back to its queue');
  console.log('PASS trial approval unlocks onboarding without completing it');
  console.log('PASS onboarding review shows full record and signed agreement');
  console.log('PASS completed onboarding has an explicit success state');
  console.log('PASS desktop and phone runtime layouts fit');
  console.log('5/5 management dashboard runtime checks passed');
}
run().catch(error=>{console.error(error);process.exit(1)});
