// Run these project-owned checks through the Browser skill against the local preview.
// No live service or source spreadsheet is used. Capture callback saves actual screenshots.
const assert=require('node:assert/strict');
function harness(page){const checks=[];return {checks,check(name,ok){assert.ok(ok,name);checks.push({name,status:'PASS'});},async click(name){await page.getByRole('button',{name,exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});await page.domSnapshot();},async heading(name){await page.getByRole('heading',{name,exact:true}).waitFor({state:'visible',timeoutMs:5000});},async role(value){await page.getByRole('combobox',{name:'Preview as',exact:true}).selectOption(value);await page.domSnapshot();},async helpers(){const d=page.locator('details').filter({has:page.getByText('Test helpers',{exact:true})});if(await d.getAttribute('open')===null)await page.getByText('Test helpers',{exact:true}).click();}};}
async function application(page,{capture=async()=>{}}={}){const {checks,check,click,heading,helpers}=harness(page);await click('Reset demo');await click('Open application form');await heading('Create with GrowthCooks.');await click('Continue with Google');await click('Continue');check('missing required application fields are rejected',(await page.locator('#form-error').innerText()).includes('Complete your name'));
await helpers();await click('Fill example application');await page.getByRole('textbox',{name:'Full name',exact:true}).fill('Ada Example');await page.getByRole('textbox',{name:'Email address',exact:true}).fill('ada@example.test');await page.getByRole('textbox',{name:'WhatsApp number',exact:true}).fill('+234 800 000 0099');await capture('application');await click('Continue');check('all eight content questions are present',await page.locator('#application-form select').count()===8);await click('Continue');check('introduction step has immutable-answer preview',await page.getByText('Review your answers',{exact:true}).count()===1);await helpers();await click('Offline: off');await click('Submit application');await page.getByText('You’re offline. Your entries are still here. Reconnect and try again.',{exact:true}).waitFor({state:'visible'});check('offline submission creates no application row',(await page.locator('#proof-counts').innerText()).startsWith('2 application records'));await click('Offline: on');await click('Submit application');await heading('Application received.');check('one confirmed submission adds one shared record',(await page.locator('#proof-counts').innerText()).startsWith('3 application records'));await capture('receipt');await click('Applications inbox');await page.getByRole('button',{name:/Ada Example/}).click();await heading('Ada Example');check('new application opens in management vibe check',await page.locator('#screening-form').count()===1);return checks;}
async function happy(page,{capture=async()=>{}}={}){const {checks,check,click,heading,role,helpers}=harness(page);await click('Reset demo');await click('1 Awaiting vibe check');await heading('Awaiting vibe check');check('count opens its filtered records',await page.locator('[data-person]').count()===1);await page.getByRole('button',{name:/Amara Example/}).click();await heading('Amara Example');await page.getByRole('combobox',{name:'Recommended brand',exact:true}).selectOption('Aura');await page.getByRole('combobox',{name:'Recommended tier',exact:true}).selectOption('Tier 1');await capture('vibe-check');await click('Save vibe check');await page.getByRole('heading',{name:'Outreach',exact:true}).waitFor({state:'visible'});check('screening acceptance opens outreach, not an automatic trial',await page.locator('#contact-form').count()===1&&await page.locator('#trial-form').count()===0);
await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_ACCEPTED_TRIAL');await click('Record contact attempt');await page.getByRole('heading',{name:'Set up the trial',exact:true}).waitFor({state:'visible'});await capture('trial-setup');await click('Start trial');await page.getByRole('heading',{name:'Trial Started',exact:true}).waitFor({state:'visible'});await click('Open creator portal');await heading('Your Aura trial');await page.getByRole('textbox',{name:'Video link',exact:true}).fill('https://www.tiktok.com/@example/video/900000000000000005');await page.getByRole('textbox',{name:'Views',exact:true}).fill('9999');await click('Submit for verification');check('below-threshold evidence is rejected',(await page.locator('#evidence-error').innerText()).includes('10,000'));await page.getByRole('textbox',{name:'Views',exact:true}).fill('10000');await helpers();await click('Use example screenshot');await capture('creator-evidence');await click('Submit for verification');await page.getByRole('heading',{name:'Your video is being checked.',exact:true}).waitFor({state:'visible'});check('proof submission does not unlock onboarding',await page.getByRole('button',{name:'Start onboarding',exact:true}).count()===0);
await role('Ella');await click('1 Evidence awaiting verification');await page.getByRole('button',{name:/Amara Example/}).click();await heading('Amara Example');check('manager sees exact submitted post',await page.getByRole('link',{name:'Open submitted video',exact:true}).getAttribute('href')==='https://www.tiktok.com/@example/video/900000000000000005');await capture('manager-evidence');await click('Verify trial success');check('verification requires explicit check',(await page.locator('#verify-error').innerText()).includes('Confirm'));await page.getByRole('checkbox',{name:'I checked the link and screenshot. This video has at least 10,000 views.',exact:true}).check();await click('Verify trial success');await page.getByRole('heading',{name:'Aura onboarding',exact:true}).waitFor({state:'visible'});check('success creates onboarding but no active membership',(await page.locator('#proof-counts').innerText()).includes('0 active memberships'));await click('Open creator onboarding');await heading('Onboarding is ready.');await click('Start onboarding');await heading('Set up for Aura');await page.getByRole('checkbox',{name:'I’ve read the brand brief.',exact:true}).check();await page.getByRole('textbox',{name:'Public Instagram or TikTok profile link',exact:true}).fill('https://www.instagram.com/example/');await click('Send setup for review');await heading('Your setup is being checked.');await role('Ella');await click('1 Brand onboarding');await page.getByRole('button',{name:/Amara Example/}).click();await page.getByRole('checkbox',{name:'I checked the creator’s brand setup and approve this membership.',exact:true}).check();await click('Complete brand onboarding');await page.getByText('Active brand membership created.',{exact:true}).waitFor({state:'visible'});check('completed brand onboarding creates exactly one membership',(await page.locator('#proof-counts').innerText()).includes('1 active memberships'));await capture('onboarding-complete');await role('creator');await heading('Your dashboard is ready.');check('creator sees only the activated brand',await page.getByRole('heading',{name:'Aura',exact:true}).count()===1);return checks;}
async function branches(page,{capture=async()=>{}}={}){const {checks,check,click,heading,role,helpers}=harness(page);await click('Reset demo');await page.getByRole('button',{name:/Amara Example/}).click();await page.getByRole('combobox',{name:'Decision',exact:true}).selectOption('Reject by management');await page.getByRole('combobox',{name:'Team rejection reason',exact:true}).selectOption('Other');await click('Save vibe check');check('Other rejection reason requires note',(await page.locator('#form-error').innerText()).includes('note'));await page.getByRole('textbox',{name:'Note',exact:true}).fill('Example review note');await click('Save vibe check');await page.getByText('Rejected by management',{exact:true}).first().waitFor({state:'visible'});check('rejection does not open outreach',await page.locator('#contact-form').count()===0);
await click('Reset demo');await page.getByRole('button',{name:/Noah Example/}).click();await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_DECLINED');await page.getByRole('combobox',{name:'Creator decline reason',exact:true}).selectOption('Compensation/pay');await click('Record contact attempt');await page.getByText('Creator declined',{exact:true}).first().waitFor({state:'visible'});check('decline cannot start a trial',await page.locator('#trial-form').count()===0);
await click('Example trial ready');await role('brand');check('brand cannot see a merely assigned trial',(await page.locator('main').innerText()).includes('0 records'));await role('Ella');await page.getByRole('button',{name:/Amara Example/}).click();await click('Share trial with brand');await page.getByText('This trial is shared with its assigned brand.',{exact:true}).waitFor({state:'visible'});await role('brand');await page.getByRole('button',{name:/Amara Example/}).click();check('shared brand view excludes original answers and internal timeline',await page.getByText('Original application',{exact:true}).count()===0&&await page.getByText('Activity timeline',{exact:true}).count()===0);await role('other');check('other agency has no GrowthCooks records',(await page.locator('main').innerText()).includes('0 records'));await capture('other-agency');await click('Expired invitation');await heading('This invitation has expired.');await capture('expired');await click('Access denied');await heading('You don’t have access to this record.');
await click('Example trial ready');await page.getByText('End trial',{exact:true}).click();await page.getByRole('textbox',{name:'Reason',exact:true}).fill('Example trial ended');await click('Confirm end trial');await page.getByRole('heading',{name:'Trial Failed',exact:true}).waitFor({state:'visible'});check('ending trial records failed outcome',await page.getByText('Example trial ended',{exact:true}).first().count()===1);await capture('trial-ended');return checks;}
async function layouts(page,{viewport=async()=>{},capture=async()=>{}}={}){const {checks,check,click,helpers}=harness(page);await click('Reset demo');for(const width of [320,390,768,1280]){await viewport({width,height:900});await click(width<600?'Phone':width<1000?'Tablet':'Desktop');check('no horizontal overflow at '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));check('readable controls at '+width,await page.locator('main button,main input,main select').evaluateAll(xs=>xs.every(x=>x.getBoundingClientRect().height>=44)));await capture('layout-'+width);}await viewport({width:390,height:844});await helpers();await click('Reduced motion: off');check('reduced-motion control applies',await page.evaluate(()=>document.body.classList.contains('reduce-motion')));await click('Open application form');await click('Continue with Google');check('page transition focuses heading',await page.evaluate(()=>document.activeElement.tagName==='H1'));return checks;}
async function recovery(page,{viewport=async()=>{},capture=async()=>{}}={}){
 const {checks,check,click,heading,role,helpers}=harness(page);
 await click('Example trial ready');await click('Open creator portal');await heading('Your Aura trial');
 await page.getByRole('textbox',{name:'Video link',exact:true}).fill('https://www.tiktok.com/@example/video/900000000000000008');
 await page.getByRole('textbox',{name:'Views',exact:true}).fill('10001');await helpers();await click('Use example screenshot');await click('Fail next save');await click('Submit for verification');
 check('failed evidence save retains input and does not enter review',await page.getByText('Could not save. Your entries are still here. Try again.',{exact:true}).count()===1&&await page.locator('#evidence-form').count()===1);
 await click('Submit for verification');await page.getByRole('heading',{name:'Your video is being checked.',exact:true}).waitFor({state:'visible'});await role('Ella');await click('1 Evidence awaiting verification');await page.getByRole('button',{name:/Amara Example/}).click();
 await click('Request correction');check('correction requires a reason',(await page.locator('#verify-error').innerText()).includes('Explain'));
 await page.getByRole('textbox',{name:'Review note (required for corrections)',exact:true}).fill('Please show the full video view count.');await click('Request correction');await click('Open creator portal');
 check('creator sees the correction message',await page.getByText('Please show the full video view count.',{exact:true}).count()===1);
 await page.getByRole('textbox',{name:'Video link',exact:true}).fill('https://www.tiktok.com/@example/video/900000000000000008');await page.getByRole('textbox',{name:'Views',exact:true}).fill('12000');await click('Use example screenshot');
 for(const width of [320,390]){await viewport({width,height:844});check('evidence form fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('evidence numeric input remains 16px at '+width,await page.locator('#proof-views').evaluateAll(xs=>xs.every(x=>getComputedStyle(x).fontSize==='16px')));}
 await capture('correction-form');await click('Submit for verification');await role('Ella');await click('1 Evidence awaiting verification');await page.getByRole('button',{name:/Amara Example/}).click();await page.getByText('Trial details and evidence history',{exact:true}).click();
 check('resubmission preserves two evidence images',await page.getByRole('img',{name:/Evidence screenshot version/}).count()===2);
 await page.getByRole('checkbox',{name:'I checked the link and screenshot. This video has at least 10,000 views.',exact:true}).check();await click('Verify trial success');await page.getByText('Cancel onboarding',{exact:true}).click();await click('Confirm cancellation');
 check('onboarding cancellation requires a reason',(await page.locator('#cancel-error').innerText()).includes('reason'));
 await page.getByRole('textbox',{name:'Reason',exact:true}).fill('Example: creator asked to pause.');await click('Confirm cancellation');check('cancelled onboarding creates no membership',(await page.locator('#proof-counts').innerText()).includes('0 active memberships'));await role('creator');await heading('Onboarding is paused.');await capture('onboarding-cancelled');
 return checks;
}
module.exports={application,happy,branches,layouts,recovery};
