// Local approval-only Browser skill runner. No external sends or server uploads.
const assert=require('node:assert/strict');
async function run(page,{viewport,capture=async()=>{}}){
 const checks=[];const check=(name,ok)=>{assert.ok(ok,name);checks.push({name,status:'PASS'});};
 const click=async(name,nav=false)=>{await (nav?page.locator('.manager-nav'):page).getByRole('button',{name,exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});};
 const value=async id=>page.locator('#'+id).evaluateAll(xs=>xs[0].value);
 await click('Reset demo');await viewport({width:390,height:844});await click('Settings');
 check('Settings contains no messaging controls',await page.locator('#template-form,#invitation-message,[role=tablist]').count()===0);
 check('Settings appears once with an icon back action',await page.getByRole('heading',{name:'Settings',exact:true}).count()===1&&await page.locator('.manager-nav').count()===0&&await page.getByRole('button',{name:'Back to workspace',exact:true}).innerText()==='');await capture('settings');
 await page.getByText('Application form',{exact:true}).click();check('required 30-second upload question visible in form editor',await page.getByRole('heading',{name:'Your 30-second introduction video',exact:true}).count()===1&&(await page.locator('#intro-question').innerText()).includes('Required'));
 await page.getByRole('heading',{name:'Your 30-second introduction video',exact:true}).click();await capture('video-question');check('nested panels are borderless',await page.locator('main .panel').evaluateAll(xs=>xs.every(x=>getComputedStyle(x).borderTopWidth==='0px'))&&await page.locator('.question-card').evaluateAll(xs=>xs.length>0&&xs.every(x=>getComputedStyle(x).borderLeftWidth==='0px'&&getComputedStyle(x).borderRightWidth==='0px')));
 await click('Add a question');await page.getByRole('textbox',{name:'Question text 9',exact:true}).fill('Favourite content style?');await page.getByRole('textbox',{name:'Question 9 option 1',exact:true}).fill('Explain\nwith examples');await page.getByRole('textbox',{name:'Question 9 option 2',exact:true}).fill('Demonstrate');await click('Save application form');check('question editing still saves',await page.getByText('Application form saved in this tab.',{exact:true}).count()===1);await click('Back to workspace');
 await click('Pipeline',true);await page.getByRole('button',{name:'CashDrive 1 accepted',exact:true}).click();
 check('business has name search and counted stages',await page.getByRole('searchbox',{name:'Search name',exact:true}).count()===1&&await page.getByRole('option',{name:'Awaiting response (1)',exact:true}).count()===1&&await page.getByRole('option',{name:'Unresponsive (0)',exact:true}).count()===1);
 check('stage selector is narrower than content',await page.locator('#pipeline-stage').evaluateAll(xs=>xs[0].getBoundingClientRect().width<xs[0].closest('main').getBoundingClientRect().width));
 await page.getByRole('searchbox',{name:'Search name',exact:true}).fill('Amara');check('no other-business search result',await page.getByText('No matching applicants.',{exact:true}).count()===1);await page.getByRole('searchbox',{name:'Search name',exact:true}).fill('Noah');await page.getByRole('combobox',{name:'Stage',exact:true}).selectOption('Awaiting response');await capture('pipeline');await page.getByRole('button',{name:/Noah Example/}).click();await click('Text Noah on WhatsApp');
 check('person opens composer not Settings',await page.locator('#invitation-message').count()===1&&await page.getByRole('heading',{name:'Settings',exact:true}).count()===0);
 const original=await value('invitation-message');check('message has correct person operator business and paragraphs',original.includes('Noah')&&original.includes('Ella')&&original.includes('CashDrive')&&original.includes('\n\n'));await page.getByRole('textbox',{name:'WhatsApp message',exact:true}).fill(original+'\n\nPlease let us know.');const href=await page.getByRole('link',{name:'Open WhatsApp',exact:true}).getAttribute('href');check('WhatsApp link has recipient number and prepared message',href.startsWith('https://wa.me/2348000000002?text=')&&decodeURIComponent(href).includes('Please let us know.'));
 await page.getByRole('link',{name:'Open WhatsApp',exact:true}).click();check('prototype does not send live WhatsApp',(await page.locator('#whatsapp-status').innerText()).includes('Nothing sent'));await capture('contact');await click('Back to applicant');await click('Back to pipeline');check('name and stage survive returning',await value('pipeline-search')==='Noah'&&await value('pipeline-stage')==='Awaiting response');
 await page.getByRole('button',{name:/Noah Example/}).click();await click('Text Noah on WhatsApp');check('person message draft survives back', (await value('invitation-message')).includes('Please let us know.'));
 await page.getByText('Edit default message for CashDrive',{exact:true}).click();await page.getByRole('textbox',{name:'Default outreach message',exact:true}).fill('Hi {name},\n\nThis is {sender} from {brand}.');await page.getByText('Test helpers',{exact:true}).click();await click('Fail next save');await click('Save default message');check('failed default save retains text',(await value('template-text')).includes('This is {sender}'));await click('Save default message');check('default saved within contact page',await page.locator('#invitation-message').count()===1&&(await value('invitation-message')).includes('Ella from CashDrive.'));
 await page.getByRole('combobox',{name:'Preview as',exact:true}).selectOption('Smith');await page.getByRole('button',{name:/Noah Example/}).click();await click('Text Noah on WhatsApp');check('another operator gets own sender and draft', (await value('invitation-message')).includes('Smith from CashDrive.')&&!(await value('invitation-message')).includes('Ella'));await click('Back to applicant');await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('UNRESPONSIVE');await click('Save outcome');await click('Back to pipeline');check('counts update after outcome',await page.getByRole('option',{name:'Unresponsive (1)',exact:true}).count()===1&&await page.getByRole('option',{name:'Awaiting response (0)',exact:true}).count()===1);await page.getByRole('combobox',{name:'Stage',exact:true}).selectOption('Unresponsive');await click('Settings');await click('Back to workspace');check('settings exit restores business filters',await value('pipeline-search')==='Noah'&&await value('pipeline-stage')==='Unresponsive');
 await click('Applicants',true);await page.getByRole('button',{name:/Amara Example/}).click();await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('NorthQuest');await page.getByRole('combobox',{name:'Tier',exact:true}).selectOption('Tier 1');await click('Save decision');await click('Open NorthQuest pipeline');await page.getByRole('button',{name:/Amara Example/}).click();await click('Text Amara on WhatsApp');check('CashDrive default never overwrote NorthQuest',(await value('invitation-message')).includes('We would like to discuss your creator trial.'));await click('Back to applicant');await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_ACCEPTED_TRIAL');await click('Save outcome');await click('Start trial');check('invitation now uses automatic stage-specific message',await value('trial-link')==='https://preview.example.test/trial/northquest/demo-invite-app-1'&&(await value('invitation-message')).includes('/trial/northquest/'));await page.getByText('Edit default message for NorthQuest',{exact:true}).click();check('invitation default requires no type selector',await page.getByRole('textbox',{name:'Default trial invitation',exact:true}).count()===1&&await page.locator('#template-kind,#template-brand').count()===0);
 await click('Preview creator invitation / dashboard');check('recipient remains assigned to NorthQuest',await page.getByRole('heading',{name:'Welcome to your NorthQuest Creator dashboard.',exact:true}).count()===1);await click('Return to manager’s place');check('return keeps invitation draft and business',await value('trial-link')==='https://preview.example.test/trial/northquest/demo-invite-app-1');
 await click('Reset demo');await click('Fill example application');await page.getByRole('textbox',{name:'Full name',exact:true}).fill('Video Review Example');await page.getByRole('textbox',{name:'Email address',exact:true}).fill('video-review@example.test');await page.getByRole('textbox',{name:'WhatsApp number',exact:true}).fill('+2348000000009');await click('Continue');await click('Continue');check('applicant sees actual required introduction upload',await page.getByLabel('Your 30-second introduction video',{exact:true}).count()===1);await click('Submit application');await click('Applicants');await page.getByRole('button',{name:/Video Review Example/}).click();check('submitted example filename is attached to this applicant review',await page.getByRole('heading',{name:'Introduction video',exact:true}).count()===1&&await page.getByText('example-introduction.mp4',{exact:true}).count()===1);await capture('review-video');
 await click('Back to applicants');await page.getByRole('combobox',{name:'Preview as',exact:true}).selectOption('other');check('different agency sees no applicant records',await page.locator('[data-person]').count()===0);await click('Reset demo');
 // Native-key activation remains unverified: the Browser locator press did not activate either
 // the new back button or the unchanged Applicants button. Do not claim this click as keyboard proof.
 for(const width of [320,390,768]){await viewport({width,height:844});await click('Pipeline',true);await page.getByRole('button',{name:'CashDrive 1 accepted',exact:true}).click();check('pipeline fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await capture('pipeline-'+width);await click('Back to pipelines');check('icon back returns to index '+width,await page.getByRole('heading',{name:'Pipeline',exact:true}).count()===1);}
 await viewport({width:390,height:844});await click('Settings');check('back icon touch target stays 44px',await page.getByRole('button',{name:'Back to workspace',exact:true}).evaluateAll(xs=>xs[0].getBoundingClientRect().width>=44&&xs[0].getBoundingClientRect().height>=44));await click('Reset demo');return checks;
}
module.exports={run};
