const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const h=fs.readFileSync(require('node:path').join(__dirname,'../prototypes/recruitment.html'),'utf8');
assert.ok(h.includes('function pipelineView('),'business name search/count model is present');
const c=vm.createContext({Date,Intl,URL});vm.runInContext(h.match(/\/\/ RECRUITMENT CORE START([\s\S]*?)\/\/ RECRUITMENT CORE END/)[1]+';this.api={pipelineView,createStore,formatMessage};',c);
const a=c.api,admin={role:'admin',agency:'growthcooks',name:'Ella'};let n=0;const test=(name,fn)=>{fn();console.log('PASS '+name);n++;};
function fixture(){const s=a.createStore();s.people=[{id:'1',agency:'growthcooks',answers:{fullName:'Noah Example'},screening:{state:'ACCEPTED_FOR_OUTREACH',brand:'CashDrive'},outreach:{state:'CONTACTED_AWAITING_RESPONSE'}},{id:'2',agency:'growthcooks',answers:{fullName:'Nora Example'},screening:{state:'ACCEPTED_FOR_OUTREACH',brand:'CashDrive'},outreach:{state:'UNRESPONSIVE'}},{id:'3',agency:'growthcooks',answers:{fullName:'Noah Other'},screening:{state:'ACCEPTED_FOR_OUTREACH',brand:'NorthQuest'},outreach:{state:'CONTACTED_AWAITING_RESPONSE'}}];return s;}
test('name search is scoped to one business and ignores case',()=>{const v=a.pipelineView(fixture(),admin,'CashDrive',' nOaH ','All stages');assert.equal(v.people.length,1);assert.equal(v.people[0].id,'1');});
test('stage counts remain business totals when name filters rows',()=>{const v=a.pipelineView(fixture(),admin,'CashDrive','Noah','All stages');assert.equal(v.total,2);assert.equal(v.counts['Contacted'],1);assert.equal(v.counts.Unresponsive,1);});
test('combined stage and name filters can return empty',()=>{assert.equal(a.pipelineView(fixture(),admin,'CashDrive','Noah','Unresponsive').people.length,0);});
test('other agency and unshared brand staff see no names or counts',()=>{for(const actor of [{...admin,agency:'other'},{role:'brand',agency:'growthcooks',brand:'CashDrive'}]){const v=a.pipelineView(fixture(),actor,'CashDrive','','All stages');assert.equal(v.people.length,0);assert.equal(v.total,0);}});
test('default contact message uses current operator and paragraphs',()=>{const s=fixture(),p=s.people[0],t=a.formatMessage(s,p,{...admin,name:'Smith'},'outreach');assert.ok(t.includes('Smith'));assert.ok(t.includes('CashDrive'));assert.ok(t.includes('\n\n'));assert.ok(!t.includes('Ella'));});
console.log(`${n}/${n} contact checks passed`);
