// Invoke through the Browser skill with a page and viewport/capture callbacks.
const assert=require('node:assert/strict');
async function run(page,{viewport,capture=async()=>{}}){
 const checks=[];const check=(name,ok)=>{assert.ok(ok,name);checks.push({name,status:'PASS'});};
 const click=async name=>{await page.getByRole('button',{name,exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});};
 const val=async id=>page.locator('#'+id).evaluateAll(xs=>xs[0].value);
 await click('Reset demo');await viewport({width:390,height:844});await click('Settings');
 check('two message tabs replace type dropdown',await page.getByRole('tab').count()===2&&await page.locator('#template-kind').count()===0);
 await page.getByRole('textbox',{name:'Template',exact:true}).fill('Outreach draft for {name}.');await page.getByRole('tab',{name:'Invitation',exact:true}).click();await page.getByRole('textbox',{name:'Template',exact:true}).fill('Invitation draft for {name}: {link}');await page.getByRole('tab',{name:'Invitation',exact:true}).press('ArrowLeft');
 check('keyboard tab switch restores outreach draft',await val('template-text')==='Outreach draft for {name}.'&&await page.getByRole('tab',{name:'Outreach',exact:true}).getAttribute('aria-selected')==='true');
 await page.getByRole('tab',{name:'Outreach',exact:true}).press('ArrowRight');check('invitation draft preserved',await val('template-text')==='Invitation draft for {name}: {link}');await click('Save template');await capture('message-tabs');
 await page.getByText('Application form',{exact:true}).click();check('separate question cards and answer fields',await page.locator('.question-card').count()===8&&await page.locator('#options-0').count()===0);
 await page.locator('[data-add-option="0"]').click();await page.getByRole('textbox',{name:'Question 1 option 3',exact:true}).fill('A longer answer\nthat stays one option.');await page.locator('[data-add-option="0"]').click();await page.getByRole('textbox',{name:'Question 1 option 4',exact:true}).fill('Fourth option');await page.getByRole('button',{name:'Remove question 1 option 2',exact:true}).click();
 check('removing an option preserves the others in order',await val('option-0-1')==='A longer answer\nthat stays one option.'&&await val('option-0-2')==='Fourth option');
 await click('Add a question');check('new question receives focus',await page.locator('#question-8').evaluateAll(xs=>document.activeElement===xs[0]));await click('Save application form');check('blank new question cannot save',(await page.locator('#settings-error').innerText()).includes('question'));
 await page.getByRole('textbox',{name:'Question text 9',exact:true}).fill('What kind of content do you enjoy?');await page.getByRole('textbox',{name:'Question 9 option 1',exact:true}).fill('Explainers');await page.getByRole('textbox',{name:'Question 9 option 2',exact:true}).fill('Demonstrations');
 await page.getByText('Test helpers',{exact:true}).click();await click('Fail next save');await click('Save application form');check('failed save keeps new question and options',await val('question-8')==='What kind of content do you enjoy?'&&await val('option-8-1')==='Demonstrations');await click('Save application form');check('form save confirmed',await page.getByText('Application form saved in this tab.',{exact:true}).count()===1);await capture('question-editor');
 await click('Open application form');await click('Continue with Google');await click('Fill example application');await click('Continue');check('added question appears as required in applicant flow',await page.getByRole('combobox',{name:'What kind of content do you enjoy?',exact:true}).evaluateAll(xs=>xs[0].required));check('multiline answer remains one option for applicant',await page.locator('#phoneQuality option').evaluateAll(xs=>xs.length===4));
 await click('Reset demo');await click('Pipeline');await page.getByRole('button',{name:'CashDrive 1 accepted',exact:true}).click();check('opened business has no switcher or other brands',await page.getByRole('heading',{name:'CashDrive',exact:true}).count()===1&&await page.locator('#workspace-business').count()===0&&!(await page.locator('main').innerText()).includes('NorthQuest'));await capture('cashdrive-only');
 await page.getByRole('button',{name:/Noah Example/}).click();check('WhatsApp action uses recipient name',await page.getByRole('button',{name:'Text Noah on WhatsApp',exact:true}).count()===1);await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_DECLINED');check('decline alone shows reason',await page.locator('#decline-fields').evaluateAll(xs=>!xs[0].hidden));await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_ACCEPTED_TRIAL');await click('Save outcome');
 const today=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',timeZone:'Africa/Lagos'}).format(new Date());check('start date is today and dates cannot be typed',await page.locator('#trial-start-date').innerText()===today&&await page.locator('#trial-form input[type=date]').count()===0);await capture('automatic-dates');await click('Start trial');
 check('CashDrive link and message use assigned brand',await val('trial-link')==='https://preview.example.test/trial/cashdrive/demo-invite-app-2'&&(await val('invitation-message')).includes('/trial/cashdrive/'));await capture('cashdrive-invitation');
 await click('Preview creator invitation / dashboard');check('same invitation opens CashDrive recipient screen',await page.getByRole('heading',{name:'Welcome to your CashDrive Creator dashboard.',exact:true}).count()===1);await click('Continue with Google');await page.getByRole('textbox',{name:'TikTok profile link (if you have one)',exact:true}).fill('https://www.tiktok.com/@example');await click('Continue to dashboard');await click('Next');await click('Next');await click('Got it');check('recipient reaches correct trial dashboard',await page.getByRole('heading',{name:'Hi, Noah.',exact:true}).count()===1);await click('Return to manager’s place');check('return restores original invitation',await page.locator('#trial-link').count()===1&&(await val('trial-link')).includes('/cashdrive/'));
 await click('Back to applicant');await click('Back to pipeline');check('back stays in CashDrive',await page.getByRole('heading',{name:'CashDrive',exact:true}).count()===1);await click('Back to pipelines');check('explicit back returns to business index',await page.getByRole('button',{name:'NorthQuest 0 accepted',exact:true}).count()===1);
 for(const width of [320,390,768]){await viewport({width,height:844});await click('Settings');if(await page.locator('#question-settings').evaluateAll(xs=>!xs[0].open))await page.getByText('Application form',{exact:true}).click();await page.locator('#question-0').click();check('settings fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await capture('settings-'+width);await click('Pipeline');}
 await viewport({width:390,height:844});await click('Reset demo');return checks;
}
module.exports={run};
