const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../prototypes/recruitment.html'),'utf8'),ctx=vm.createContext({Date,Intl,URL});
vm.runInContext(html.match(/\/\/ RECRUITMENT CORE START([\s\S]*?)\/\/ RECRUITMENT CORE END/)[1]+';this.api={createStore,apply,screening,contact,startTrial,distributionList,pipelineList,saveMessageTemplate,formatMessage,finishEarly};',ctx);
const a=ctx.api,admin={name:'Ella',role:'admin',agency:'growthcooks'},now='2026-09-06T10:00:00+01:00';
const answers={fullName:'Demo Applicant',email:'demo@example.test',whatsappRaw:'+2348000000011',city:'Ibadan',state:'Oyo',ageConfirmed:true,phoneQuality:'Yes',editingSkills:'Yes',cameraComfort:'Yes',experience:'Regularly',ugcComfort:'Yes',briefComfort:'Comfortable',dailyCapacity:'Yes',availability:'Immediately',introVideo:{name:'demo.mp4',type:'video/mp4',size:1024}};
let total=0;const test=(name,fn)=>{fn();console.log('PASS '+name);total++;};
function setup(){const s=a.createStore();assert.ok(a.apply(s,'growthcooks',answers,'demo',now).ok);return {s,p:s.people[0]};}
test('pending applicants are distribution-only',()=>{const {s,p}=setup();assert.equal(a.distributionList(s,admin,'pending').length,1);a.screening(s,admin,p.id,{accepted:true,brand:'NorthQuest',tier:'Tier 1'},now);assert.equal(a.distributionList(s,admin,'pending').length,0);assert.equal(a.pipelineList(s,admin,'NorthQuest').length,1);assert.equal(a.pipelineList(s,admin,'CashDrive').length,0);assert.equal(s.people.length,1);});
test('rejected stays separate from every brand pipeline',()=>{const {s,p}=setup();a.screening(s,admin,p.id,{accepted:false,reason:'Video quality'},now);assert.equal(a.distributionList(s,admin,'pending').length,0);assert.equal(a.distributionList(s,admin,'rejected').length,1);for(const brand of ['NorthQuest','CashDrive','Aura'])assert.equal(a.pipelineList(s,admin,brand).length,0);});
test('other agency cannot see applicant or business lists',()=>{const {s,p}=setup(),other={...admin,agency:'other'};assert.equal(a.distributionList(s,other,'pending').length,0);a.screening(s,admin,p.id,{accepted:true,brand:'Aura',tier:'Tier 1'},now);assert.equal(a.pipelineList(s,other,'Aura').length,0);assert.equal(a.pipelineList(s,{role:'brand',agency:'growthcooks',brand:'Aura'},'Aura').length,0);});
test('trial start cannot change assigned brand or tier',()=>{const {s,p}=setup();a.screening(s,admin,p.id,{accepted:true,brand:'NorthQuest',tier:'Tier 1'},now);a.contact(s,admin,p.id,{channel:'WhatsApp',result:'CREATOR_ACCEPTED_TRIAL'},now);const trial={brand:'CashDrive',tier:'Tier 1',contentType:'Video',start:'2026-09-06',due:'2026-09-13'};assert.equal(a.startTrial(s,admin,p.id,trial,now).ok,false);assert.equal(a.startTrial(s,admin,p.id,{...trial,brand:'NorthQuest',tier:'Tier 2'},now).ok,false);assert.ok(a.startTrial(s,admin,p.id,{...trial,brand:'NorthQuest'},now).ok);});
test('message templates are brand-scoped, versioned and restricted',()=>{const {s,p}=setup();a.screening(s,admin,p.id,{accepted:true,brand:'NorthQuest',tier:'Tier 1'},now);const before=a.formatMessage(s,p,admin,'outreach');assert.equal(a.saveMessageTemplate(s,{...admin,agency:'other'},'NorthQuest','outreach','Hi {name}',now).ok,false);assert.ok(a.saveMessageTemplate(s,admin,'NorthQuest','outreach','Hi {name}, {sender} here from {brand}.',now).ok);assert.equal(a.formatMessage(s,p,admin,'outreach'),'Hi Demo, Ella here from NorthQuest.');assert.notEqual(before,a.formatMessage(s,p,admin,'outreach'));assert.equal(s.config.messages.NorthQuest.outreach.version,2);assert.equal(a.saveMessageTemplate(s,admin,'NorthQuest','outreach','Hi {password}',now).ok,false);});
test('UGC No finishes without later answers or video',()=>{const s=a.createStore(),early={...answers,ugcComfort:'No'};delete early.introVideo;delete early.briefComfort;delete early.dailyCapacity;delete early.availability;assert.ok(a.finishEarly(s,'growthcooks',early,'early',now).ok);assert.equal(s.people[0].screening.state,'EARLY_FINISH');assert.equal(a.distributionList(s,admin,'pending').length,0);assert.equal(a.pipelineList(s,admin,'NorthQuest').length,0);assert.ok(Object.isFrozen(s.people[0].answers));});
test('early finish cannot bypass earlier required fields or replay a completed form',()=>{const s=a.createStore();assert.equal(a.finishEarly(s,'growthcooks',{...answers,ugcComfort:'No',email:''},'bad',now).ok,false);assert.equal(a.finishEarly(s,'growthcooks',{...answers,ugcComfort:'Yes'},'bad',now).ok,false);a.apply(s,'growthcooks',answers,'completed',now);assert.equal(a.finishEarly(s,'growthcooks',{...answers,ugcComfort:'No'},'completed',now).ok,false);assert.equal(s.people[0].screening.state,'PENDING_REVIEW');});
test('early completion cannot masquerade as full submission or retain later data',()=>{const s=a.createStore();a.finishEarly(s,'growthcooks',{...answers,ugcComfort:'No'},'same',now);assert.equal(a.apply(s,'growthcooks',answers,'same',now).ok,false);assert.equal(s.people[0].answers.introVideo,undefined);assert.equal(s.people[0].answers.availability,undefined);});
console.log(`${total}/${total} distribution checks passed`);
