// Approval-only Browser skill runner: no real messages, uploads or persisted data.
const assert=require('node:assert/strict');
async function run(page,{viewport,capture=async()=>{}}){
 const checks=[];const check=(name,ok)=>{assert.ok(ok,name);checks.push({name,status:'PASS'});};
 const click=async(name,nav=false)=>{await (nav?page.locator('.manager-nav'):page).getByRole('button',{name,exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});};
 const value=async id=>page.locator('#'+id).evaluateAll(xs=>xs[0].value);
 await click('Reset demo');await viewport({width:390,height:844});check('Applicants heading not repeated visibly',await page.locator('main h1').evaluateAll(xs=>xs[0].classList.contains('sr-only')));await page.getByRole('button',{name:/Amara Okafor/}).click();
 check('realistic full name below back icon',await page.locator('.person-heading').evaluateAll(xs=>xs[0].querySelector('h1').getBoundingClientRect().top>xs[0].querySelector('button').getBoundingClientRect().bottom));check('contact lines have deliberate spacing',await page.locator('.contact-summary').evaluateAll(xs=>getComputedStyle(xs[0]).rowGap==='16px'));await capture('review');
 await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('Aura');await page.getByRole('combobox',{name:'Tier',exact:true}).selectOption('Tier 1');await click('Save');await click('Open Aura pipeline');await page.getByRole('button',{name:/Amara Okafor/}).click();
 check('brand then person then contact details',await page.locator('.person-heading').evaluateAll(xs=>xs[0].querySelector('.person-brand').textContent==='Aura'&&xs[0].querySelector('.person-brand').getBoundingClientRect().bottom<=xs[0].querySelector('h1').getBoundingClientRect().top));check('uncontacted outcome is not pre-recorded',await value('contact-result')==='');check('Outreach heading removed',await page.getByRole('heading',{name:'Outreach',exact:true}).count()===0);
 check('WhatsApp action after outcome',await page.locator('#contact-form').evaluateAll(xs=>xs[0].querySelector('[data-action=outreach-message]').getBoundingClientRect().top>xs[0].querySelector('#contact-result').getBoundingClientRect().bottom));await capture('contact-outcome');await click('Text Amara on WhatsApp');check('message says first name and allows links', (await value('invitation-message')).startsWith('Hi Amara,')&&(await value('invitation-message')).includes('Ella from the Aura team'));await page.getByRole('textbox',{name:'WhatsApp message',exact:true}).fill('Hi Amara,\n\nHere is our brief: https://example.test/brief');check('custom link is in prepared WhatsApp message',decodeURIComponent(await page.getByRole('link',{name:'Open WhatsApp',exact:true}).getAttribute('href')).includes('https://example.test/brief'));await click('Back to applicant');
 await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_DECLINED');await page.getByRole('combobox',{name:'Creator decline reason',exact:true}).selectOption('Workload/video volume');await click('Save');check('decline lands in a visible list and confirmation',await page.getByRole('heading',{name:'Aura',exact:true}).count()===1&&(await page.locator('main').innerText()).includes('Amara declined. Reason: Workload/video volume.')&&await value('pipeline-stage')==='Declined');await capture('declined-business');
 check('exact five stage filters',await page.locator('#pipeline-stage option').evaluateAll(xs=>JSON.stringify(xs.map(x=>x.value))===JSON.stringify(['All stages','Contacted','Cannot be reached','Unresponsive','Declined','Trial started'])));await click('Applicants',true);await click('Declined');check('declined in own Applicants queue',await page.getByRole('button',{name:/Amara Okafor.*Workload\/video volume/}).count()===1);await page.getByRole('button',{name:/Amara Okafor/}).click();check('decline review shows reason and recorder',(await page.locator('.decline-summary').innerText()).includes('Recorded by Ella')&&(await page.locator('.decline-summary').innerText()).includes('Workload/video volume'));await capture('declined-record');await click('Back to applicants');await click('Rejected');check('declined is not team rejected',await page.getByRole('button',{name:/Amara Okafor/}).count()===0);await click('Accepted');check('declined excluded from accepted summary',await page.getByRole('button',{name:'Aura 0 accepted',exact:true}).count()===1);
 await click('Pipeline',true);await page.getByRole('button',{name:'CashDrive 1 people',exact:true}).click();await page.getByRole('searchbox',{name:'Search name',exact:true}).fill('Noah');await page.getByRole('combobox',{name:'Stage',exact:true}).selectOption('Contacted');await page.getByRole('button',{name:/Noah Adeyemi/}).click();await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_ACCEPTED_TRIAL');await click('Save');check('start trial has no end date',await page.locator('#trial-end-date,#trial-form input[type=date]').count()===0&&await page.getByRole('button',{name:'Start trial',exact:true}).count()===1);await click('Start trial');const invitation=await value('trial-link');await click('Back to applicant');check('no End trial control',await page.getByText('End trial',{exact:true}).count()===0);await click('Back to pipeline');check('prior Contacted filter preserved and Trial started count updated',await value('pipeline-stage')==='Contacted'&&await page.getByRole('option',{name:'Trial started (1)',exact:true}).count()===1);await page.getByRole('combobox',{name:'Stage',exact:true}).selectOption('Trial started');await capture('pipeline');
 await click('Settings');await page.getByText('Brands',{exact:true}).click();await click('Rename CashDrive');await page.getByRole('textbox',{name:'Brand name',exact:true}).fill('Discard this');await click('Cancel');await click('Rename CashDrive');check('cancel rename discards unsaved text',await value('rename-brand-1')==='CashDrive');await page.getByRole('textbox',{name:'Brand name',exact:true}).fill('Aura');await page.locator('.rename-brand-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden'});check('duplicate brand rename rejected',(await page.locator('.rename-brand-form [role=alert]').innerText()).includes('unique'));await page.getByRole('textbox',{name:'Brand name',exact:true}).fill('CashDrive Motors');await page.getByText('Test helpers',{exact:true}).click();await click('Fail next save');await page.locator('.rename-brand-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden'});check('rename failed save keeps text',await value('rename-brand-1')==='CashDrive Motors');await page.locator('.rename-brand-form').getByRole('button',{name:'Save',exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden'});check('brand rename visible',await page.getByText('CashDrive Motors',{exact:true}).count()===1);await capture('brands');await click('Back to workspace');check('renamed page preserves list and filters',await page.getByRole('heading',{name:'CashDrive Motors',exact:true}).count()===1&&await value('pipeline-search')==='Noah');await page.getByRole('button',{name:/Noah Adeyemi/}).click();await click('Prepare WhatsApp invitation');check('rename does not break recipient link',await value('trial-link')===invitation&&(await value('invitation-message')).includes('CashDrive Motors'));await click('Preview creator invitation / dashboard');check('creator sees renamed brand',await page.getByRole('heading',{name:'Welcome to your CashDrive Motors Creator dashboard.',exact:true}).count()===1);await click('Return to manager’s place');
 await click('Reset demo');await click('Open application form');await click('Continue with Google');check('agency application branding',(await page.locator('.appbar').innerText()).includes('GrowthCooks Marketing Agency')&&!((await page.locator('.appbar').innerText())==='TDT'));check('all identity fields have required marks',await page.locator('#application-form .required-mark').count()===6);await page.getByRole('textbox',{name:'Full name',exact:true}).fill('Ada Draft');check('automatic draft status', (await page.locator('#draft-status').innerText()).includes('saved automatically'));await click('Applicants');await click('Open application form');check('draft survives navigation without explicit save',await value('fullName')==='Ada Draft');await capture('application');await click('Fill example application');await click('Continue');check('every shown content question has required mark',await page.locator('#application-form select').count()===await page.locator('#application-form .required-mark').count());await click('Continue');check('video required final message optional',await page.locator('#introVideo').getAttribute('aria-required')==='true'&&await page.locator('#additionalInfo').getAttribute('required')===null&&await page.locator('#application-form .required-mark').count()===1);await capture('upload');
 await click('Reset demo');for(const width of [320,390,768]){await viewport({width,height:844});check('Applicants fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:/Amara Okafor/}).click();check('person detail fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('Save is compact but touchable '+width,await page.locator('#screening-form button.primary').evaluateAll(xs=>{const r=xs[0].getBoundingClientRect();return r.height>=44&&r.width<xs[0].closest('main').getBoundingClientRect().width}));await capture('person-'+width);await click('Back to applicants');}
 await viewport({width:390,height:844});await click('Reset demo');return checks;
}
module.exports={run};
