// Existing approval prototype. Use Browser skill; never sends messages or uploads files.
const assert=require('node:assert/strict');
async function run(page,{viewport,capture=async()=>{}}){
 const checks=[];const check=(name,value)=>{assert.ok(value,name);checks.push({name,status:'PASS'});};
 const click=async(name,nav=false)=>{await (nav?page.locator('.manager-nav'):page).getByRole('button',{name,exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});};
 const heading=async name=>page.getByRole('heading',{name,exact:true}).waitFor({state:'visible'});
 await click('Reset demo');for(const width of [320,390]){await viewport({width,height:844});await click('Pipeline',true);await click('CashDrive 1 people');check('business below back '+width,await page.locator('.business-heading').evaluateAll(xs=>xs[0].querySelector('h1').getBoundingClientRect().top>xs[0].querySelector('button').getBoundingClientRect().bottom));check('business fits phone '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await capture('business-'+width);await click('Back to pipelines');}
 await click('Next: trial & onboarding (example)');await heading('Welcome to your CashDrive Creator dashboard.');await capture('invitation');await click('Continue with Google');await click('Continue to dashboard');check('trial setup requires profile',(await page.locator('#setup-error').innerText()).length>0);await page.getByRole('textbox',{name:'TikTok profile link (if you have one)',exact:true}).fill('https://www.tiktok.com/@example');await click('Continue to dashboard');await click('Next');await click('Next');await click('Got it');await heading('Hi, Noah.');check('same recipient completes mandatory walkthrough',await page.getByRole('heading',{name:'Hi, Noah.',exact:true}).count()===1);await capture('trial-dashboard');
 await click('Log a video');const link='https://www.tiktok.com/@example/video/900000000000000007';await page.getByRole('textbox',{name:'TikTok link',exact:true}).fill(link);await click('Submit video');check('video saved before proof',(await page.locator('main').innerText()).includes('Video saved.'));await click('Back to dashboard');await click('Submit for review');await page.getByRole('combobox',{name:'Choose a logged video',exact:true}).selectOption({index:1});check('proof opens exact logged content link',await page.getByRole('link',{name:'Open selected video',exact:true}).getAttribute('href')===link);await page.getByRole('textbox',{name:'Views',exact:true}).fill('10000');await click('Submit for verification');check('screenshot is mandatory',await page.locator('#evidence-form').count()===1&&(await page.locator('#evidence-error').innerText()).length>0);await page.getByText('Test helpers',{exact:true}).click();await click('Use example screenshot');await click('Fail next save');await click('Submit for verification');check('failed proof save retains selected video and image',await page.getByRole('img',{name:'Screenshot ready to submit',exact:true}).count()===1&&await page.getByRole('link',{name:'Open selected video',exact:true}).getAttribute('href')===link);await capture('evidence-retry');await click('Submit for verification');check('creator sees review pending',await page.getByText('Your video is being checked.',{exact:true}).count()===1);check('no membership before verification',(await page.locator('#proof-counts').innerText()).includes('0 active memberships'));
 await click('Return to manager’s place');await heading('Noah Adeyemi');check('manager sees exact submitted video',await page.getByRole('link',{name:'Open submitted video',exact:true}).getAttribute('href')===link);await click('Verify trial success');check('management must check evidence',(await page.locator('#verify-error').innerText()).includes('Confirm'));await page.getByRole('textbox',{name:'Review note (required for corrections)',exact:true}).fill('Please show the full view count.');await click('Request correction');await click('Preview creator invitation / dashboard');await click('Submit for review');check('creator sees correction',(await page.locator('main').innerText()).includes('Please show the full view count.'));await page.getByRole('combobox',{name:'Choose a logged video',exact:true}).selectOption({index:1});await page.getByRole('textbox',{name:'Views',exact:true}).fill('12000');await click('Use example screenshot');await click('Submit for verification');await click('Return to manager’s place');await page.getByRole('checkbox',{name:'I checked the link and screenshot. This video has at least 10,000 views.',exact:true}).check();await click('Verify trial success');check('onboarding created but no active membership',(await page.locator('main').innerText()).includes('CashDrive onboarding')&&(await page.locator('#proof-counts').innerText()).includes('0 active memberships'));await page.getByText('History',{exact:true}).click();check('audit trail retained',(await page.locator('.timeline').innerText()).includes('Evidence correction requested')&&(await page.locator('.timeline').innerText()).includes('Trial successful'));await capture('manager-history');
 await click('Preview creator invitation / dashboard');await heading('Onboarding is ready.');await capture('onboarding-ready');await click('Start onboarding');await heading('Set up for CashDrive');await click('Send setup for review');check('onboarding refuses incomplete setup',(await page.locator('#tasks-error').innerText()).length>0);await page.getByRole('checkbox',{name:'I confirm this is the profile I will use for this brand.',exact:true}).check();await page.getByRole('textbox',{name:'Public Instagram or TikTok profile link',exact:true}).fill('https://www.instagram.com/example/');await capture('brand-setup');await click('Send setup for review');await heading('Your setup is being checked.');await click('Return to manager’s place');check('manager sees submitted profile',await page.getByRole('link',{name:'Open public profile',exact:true}).getAttribute('href')==='https://www.instagram.com/example/');await click('Complete brand onboarding');check('active membership still needs manager check',(await page.locator('#onboarding-error').innerText()).length>0);await page.getByRole('checkbox',{name:'I checked the creator’s brand setup and approve this membership.',exact:true}).check();await click('Complete brand onboarding');check('exactly one local membership',(await page.locator('#proof-counts').innerText()).includes('1 active memberships'));await click('Preview creator invitation / dashboard');await heading('Your dashboard is ready.');check('active dashboard boundary remains explicit',(await page.locator('main').innerText()).includes('This preview ends at membership activation.'));await capture('membership-ready');check('onboarding result fits phone',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));return checks;
}
async function deepLink(tab){
 const url='http://127.0.0.1:4173/recruitment.html';
 const welcome=()=>tab.playwright.getByRole('heading',{name:'Welcome to your CashDrive Creator dashboard.',exact:true}).waitFor({state:'visible'});
 await tab.goto(url+'#trial-onboarding');await tab.reload();await welcome();
 await tab.goto(url);await tab.playwright.getByRole('button',{name:'Reset demo',exact:true}).click();
 await tab.goto(url+'#trial-onboarding');await welcome();
 return [{name:'direct next-phase link on reload',status:'PASS'},{name:'next-phase link on already-open page',status:'PASS'}];
}
module.exports={run,deepLink};
