const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../prototypes/recruitment.html'),'utf8');
const ctx=vm.createContext({Date,Intl,URL});
vm.runInContext(html.match(/\/\/ RECRUITMENT CORE START([\s\S]*?)\/\/ RECRUITMENT CORE END/)[1]+';this.api={createStore,normalizePhone,apply,screening,contact,startTrial,updateForm,addBrand,acceptInvitation,saveTrialSetup,submitBonus};',ctx);
const a=ctx.api,admin={name:'Uyi',role:'admin',agency:'growthcooks'},now='2026-09-06T10:00:00+01:00';
let total=0;function test(name,fn){fn();console.log('PASS '+name);total++;}
const ans={fullName:'Test Creator',email:'test@example.test',whatsappRaw:'+2348000000001',city:'Ibadan',state:'Oyo',ageConfirmed:true,phoneQuality:'Yes',editingSkills:'Yes',cameraComfort:'Yes',experience:'Regularly',ugcComfort:'Yes',briefComfort:'Comfortable',dailyCapacity:'Yes',availability:'Immediately',introVideo:{name:'intro.mp4',type:'video/mp4',size:1024}};
function setup(brand='NorthQuest'){const s=a.createStore();assert.ok(a.apply(s,'growthcooks',ans,'one',now).ok);const p=s.people[0];a.screening(s,admin,p.id,{accepted:true,brand,tier:'Tier 1',reason:'Video quality'},now);a.contact(s,admin,p.id,{channel:'WhatsApp',result:'CREATOR_ACCEPTED_TRIAL',reason:'Compensation/pay'},now);assert.ok(a.startTrial(s,admin,p.id,{brand,tier:'Tier 1',contentType:'Video',start:'2026-09-04',due:'2026-09-11'},now).ok);return {s,p,actor:{role:'creator',name:'Test Creator',agency:'growthcooks',person:p.person}};}
test('WhatsApp requires plus and exactly thirteen digits',()=>{assert.equal(a.normalizePhone('+2348000000001'),'+2348000000001');for(const x of ['+234800000000','+23480000000011','2348000000001','+abcdefghijklm'])assert.equal(a.normalizePhone(x),null);});
test('every fixed answer is required, apart from final message',()=>{for(const id of Object.keys(ans)){const s=a.createStore();assert.equal(a.apply(s,'growthcooks',{...ans,[id]:undefined},id,now).ok,false,id);}assert.ok(a.apply(a.createStore(),'growthcooks',ans,'valid',now).ok);});
test('form edits are scoped, versioned and do not rewrite answers',()=>{const {s,p}=setup(),before=JSON.stringify(p.answers);const q=JSON.parse(JSON.stringify(s.config.questions));q[0][1]='Your camera access?';assert.equal(a.updateForm(s,{...admin,agency:'elsewhere'},q,now).ok,false);assert.ok(a.updateForm(s,admin,q,now).ok);assert.equal(s.config.version,2);assert.equal(JSON.stringify(p.answers),before);assert.notEqual(p.answers.formDefinition.questions[0][1],q[0][1]);});
test('new brands require agency admin and have no implied bonus schedule',()=>{const s=a.createStore();assert.equal(a.addBrand(s,{role:'creator',agency:'growthcooks'},'New brand',now).ok,false);assert.ok(a.addBrand(s,admin,'New brand',now).ok);assert.equal(a.addBrand(s,admin,'new brand',now).ok,false);assert.ok(s.config.brands.includes('New brand'));});
test('accepted branches do not retain rejection or decline reasons',()=>{const {p}=setup();assert.equal(p.screening.reason,undefined);assert.equal(p.contacts[0].reason,null);assert.equal(p.outreach.reason,null);});
test('trial starts without coach or brief and prepares a bound invitation',()=>{const {p}=setup();assert.equal(p.trial.coach,undefined);assert.equal(p.trial.brief,undefined);assert.equal(p.invitation.email,ans.email);assert.equal(p.invitation.state,'READY');assert.equal(p.trial.setup,undefined);});
test('invitation cannot be claimed with another email or expired token',()=>{const {s,p,actor}=setup();assert.equal(a.acceptInvitation(s,actor,p.id,'other@example.test',p.invitation.token,now).ok,false);assert.equal(a.acceptInvitation(s,actor,p.id,ans.email,'wrong',now).ok,false);assert.equal(a.acceptInvitation(s,actor,p.id,ans.email,p.invitation.token,'2026-09-15T10:00:00+01:00').ok,false);assert.ok(a.acceptInvitation(s,actor,p.id,ans.email,p.invitation.token,now).ok);});
test('trial setup needs invitation and at least one valid public platform profile',()=>{const {s,p,actor}=setup();assert.equal(a.saveTrialSetup(s,actor,p.id,{tiktok:'https://www.tiktok.com/@demo'},now).ok,false);a.acceptInvitation(s,actor,p.id,ans.email,p.invitation.token,now);assert.equal(a.saveTrialSetup(s,actor,p.id,{},now).ok,false);assert.equal(a.saveTrialSetup(s,actor,p.id,{tiktok:'https://malicious.test'},now).ok,false);assert.ok(a.saveTrialSetup(s,actor,p.id,{tiktok:'https://www.tiktok.com/@demo'},now).ok);assert.equal(p.trial.setup.tiktok,'https://www.tiktok.com/@demo');});
const claim={platform:'tiktok',link:'https://www.tiktok.com/@demo/video/100001',views:'100000',date:'2026-09-05',file:{name:'proof.png',type:'image/png',size:1024,url:'data:image/png;base64,test'}};
test('trial bonuses available for NorthQuest and CashDrive, not Aura',()=>{for(const brand of ['NorthQuest','CashDrive','Aura']){const {s,p,actor}=setup(brand);assert.equal(a.submitBonus(s,actor,p.id,claim,now).ok,brand!=='Aura');assert.equal(p.onboarding,null);assert.equal(p.trial.state,'STARTED');}});
test('bonus requires exact platform link, 100k and screenshot, independently of qualification',()=>{const {s,p,actor}=setup();for(const patch of [{views:'99999'},{file:null},{platform:'facebook'},{platform:'instagram'},{date:'2026-09-01'}])assert.equal(a.submitBonus(s,actor,p.id,{...claim,...patch},now).ok,false);assert.ok(a.submitBonus(s,actor,p.id,claim,now).ok);assert.equal(a.submitBonus(s,actor,p.id,claim,now).ok,false);assert.ok(a.submitBonus(s,actor,p.id,{...claim,platform:'instagram',link:'https://www.instagram.com/reel/example/'},now).ok);assert.equal(p.bonuses.length,2);assert.equal(p.bonuses[0].amount,null);assert.equal(p.onboarding,null);assert.equal(p.evidence.length,0);});
test('bonus rejects another creator and another agency',()=>{const {s,p,actor}=setup();assert.equal(a.submitBonus(s,{...actor,person:'stranger'},p.id,claim,now).ok,false);assert.equal(a.submitBonus(s,{...admin,agency:'other'},p.id,claim,now).ok,false);});
console.log(`${total}/${total} revision 2 core checks passed`);
