// Run against the local approval prototype through the Browser skill only.
const assert=require('node:assert/strict');
async function run(page,{viewport,capture=async()=>{}}){
 const checks=[];const check=(name,ok)=>{assert.ok(ok,name);checks.push({name,status:'PASS'});};
 const click=async(name,nav=false)=>{await (nav?page.locator('.manager-nav'):page).getByRole('button',{name,exact:true}).click();await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});await page.domSnapshot();};
 const role=async v=>{await page.getByRole('combobox',{name:'Preview as',exact:true}).selectOption(v);await page.domSnapshot();};
 await click('Reset demo');await viewport({width:390,height:844});
 check('Applicants has no search or repeated agency subtitle',await page.locator('main input[type=search]').count()===0&&!(await page.locator('main').innerText()).includes('GrowthCooks Marketing Agency'));
 check('only pending applicant is in distribution',await page.locator('[data-person]').count()===1&&(await page.locator('[data-person]').innerText()).includes('Amara'));
 check('compact phone row stays between 44 and 80 pixels',await page.locator('.person').evaluateAll(xs=>xs.every(x=>x.getBoundingClientRect().height>=44&&x.getBoundingClientRect().height<=80)));
 check('phone title is 22px and applicant name 16px',await page.locator('main h1').evaluateAll(xs=>getComputedStyle(xs[0]).fontSize==='22px')&&await page.locator('.person strong').evaluateAll(xs=>getComputedStyle(xs[0]).fontSize==='16px'));
 await capture('applicants');await click('Pipeline',true);await page.getByRole('button',{name:'CashDrive 1 accepted',exact:true}).click();
 check('CashDrive lists Noah only',await page.locator('[data-person]').count()===1&&(await page.locator('[data-person]').innerText()).includes('Noah'));await capture('cashdrive');
 await click('Back to pipelines');await page.getByRole('button',{name:'Aura 0 accepted',exact:true}).click();check('Aura is separate and empty',await page.locator('[data-person]').count()===0);
 await click('Applicants',true);await page.getByRole('button',{name:/Amara Example/}).click();
 check('vibe check shows intro and hides preliminary answers',await page.getByRole('heading',{name:'Introduction video',exact:true}).count()===1&&await page.getByText('Original application',{exact:true}).count()===0);
 await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('NorthQuest');await page.getByRole('combobox',{name:'Tier',exact:true}).selectOption('Tier 1');await click('Save decision');
 check('acceptance shows movement, not outreach inside Applicants',await page.getByRole('heading',{name:'Accepted',exact:true}).count()===1&&await page.locator('#contact-form').count()===0);
 await click('Review next applicant');check('accepted person leaves pending queue',await page.locator('[data-person]').count()===0);
 await click('Accepted');await page.getByRole('button',{name:'NorthQuest 1 accepted',exact:true}).click();await page.getByRole('button',{name:/Amara Example/}).click();
 check('assigned business opens outreach without old video or answers',await page.locator('#contact-form').count()===1&&await page.getByRole('heading',{name:'Introduction video',exact:true}).count()===0&&!(await page.locator('main').innerText()).includes('Access to a smartphone'));
 await capture('northquest-outreach');await click('Text Amara on WhatsApp');await page.getByRole('link',{name:'Open WhatsApp',exact:true}).click();check('WhatsApp opens mock composer not live messaging',(await page.locator('#whatsapp-status').innerText()).includes('Nothing sent'));
 await click('Edit message template');await page.getByRole('textbox',{name:'Template',exact:true}).fill('Hello {name}, {sender} here from {brand}.');
 await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('CashDrive');await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('NorthQuest');
 check('template draft survives business switch without changing target',await page.locator('#template-text').evaluateAll(xs=>xs[0].value==='Hello {name}, {sender} here from {brand}.')&&await page.locator('#template-brand').evaluateAll(xs=>xs[0].value==='NorthQuest'));
 await click('Save template');await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('CashDrive');check('NorthQuest edit did not overwrite CashDrive',await page.locator('#template-text').evaluateAll(xs=>xs[0].value!=='Hello {name}, {sender} here from {brand}.'));
 await click('Pipeline',true);await page.getByRole('button',{name:'NorthQuest 1 accepted',exact:true}).click();await page.getByRole('button',{name:/Amara Example/}).click();await page.getByRole('combobox',{name:'Outcome',exact:true}).selectOption('CREATOR_ACCEPTED_TRIAL');await click('Save outcome');
 check('accepted trial has fixed brand and tier',await page.locator('#trial-form').count()===1&&await page.locator('#trial-brand,#trial-tier,#trial-brief,#trial-coach').count()===0&&await page.locator('#contact-form').count()===0);
 await click('Start trial');await capture('trial-invitation');await click('Edit message template');check('invitation edit opens correct template context',await page.locator('#template-brand').evaluateAll(xs=>xs[0].value==='NorthQuest')&&await page.getByRole('tab',{name:'Invitation',exact:true}).getAttribute('aria-selected')==='true');
 await click('Pipeline',true);await page.getByRole('button',{name:'NorthQuest 1 accepted',exact:true}).click();await page.getByRole('button',{name:/Amara Example/}).click();await click('Back to pipeline');check('Back restores brand context',await page.getByRole('heading',{name:'NorthQuest',exact:true}).count()===1&&await page.locator('#workspace-business').count()===0);
 await role('other');check('other agency sees no records',await page.locator('[data-person]').count()===0);await role('Uyi');await click('Settings',true);check('Uyi can edit templates',await page.locator('#template-form').count()===1);
 await click('Reset demo');await page.getByRole('button',{name:/Amara Example/}).click();await page.getByRole('combobox',{name:'Decision',exact:true}).selectOption('Reject');await page.getByRole('combobox',{name:'Team rejection reason',exact:true}).selectOption('Video quality');await click('Save decision');check('rejection is in its own list',(await page.locator('[data-person]').innerText()).includes('Rejected'));await click('To review');check('rejected person is not pending',await page.locator('[data-person]').count()===0);
 await click('Reset demo');await page.getByText('Test helpers',{exact:true}).click();await click('Fill example application');await page.getByRole('textbox',{name:'Full name',exact:true}).fill('Draft Example');await click('Continue');await page.getByRole('combobox',{name:'Are you comfortable creating UGC videos?',exact:true}).selectOption('No');await page.getByRole('heading',{name:'Thank you for applying.',exact:true}).waitFor({state:'visible'});check('UGC No ends before video and has no contact promise',await page.locator('#introVideo').count()===0&&!(await page.locator('main').innerText()).includes('WhatsApp'));await capture('early-ending');
 await click('Open application form');await click('Continue with Google');await page.getByRole('textbox',{name:'Full name',exact:true}).fill('Saved Draft');await click('Applicants');await click('Open application form');check('in-tab draft survives leaving and returning',await page.locator('#fullName').evaluateAll(xs=>xs[0].value==='Saved Draft'));
 await click('Fill example application');await click('Continue');await click('Offline: off');await page.getByRole('combobox',{name:'Are you comfortable creating UGC videos?',exact:true}).selectOption('No');await page.getByText('Saving…',{exact:true}).waitFor({state:'hidden',timeoutMs:5000});check('failed early ending reports offline',(await page.locator('#form-error').innerText()).includes('offline'));await page.getByRole('combobox',{name:'Are you comfortable creating UGC videos?',exact:true}).selectOption('Yes');check('changing No back to Yes restores later questions',await page.locator('#briefComfort,#dailyCapacity,#availability').count()===3);await click('Offline: on');
 await click('Fill example application');await click('Continue');await click('Continue');await click('Offline: off');await click('Submit application');check('offline keeps full form for retry',(await page.locator('#form-error').innerText()).includes('offline'));await click('Offline: on');await click('Submit application');check('full ending mentions WhatsApp',await page.getByText('If shortlisted, we will contact you on WhatsApp.',{exact:true}).count()===1);await capture('full-ending');
 await click('Applicants');for(const width of [320,390,768,1280]){await viewport({width,height:844});await click(width<600?'Phone':width<1000?'Tablet':'Desktop');check('Applicants fits '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await capture('layout-'+width);}
 await viewport({width:390,height:844});await click('Phone');check('navigation controls retain touch targets',await page.locator('.manager-nav button').evaluateAll(xs=>xs.every(x=>x.getBoundingClientRect().height>=44)));
 return checks;
}
module.exports={run};
