const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../prototypes/recruitment.html'),'utf8');
const ctx=vm.createContext({Date,Intl,URL});vm.runInContext(html.match(/\/\/ RECRUITMENT CORE START([\s\S]*?)\/\/ RECRUITMENT CORE END/)[1]+';this.a={createStore,apply,screening,contact,startTrial,pipelineStage,pipelineView,distributionList,renameBrand,brandLabel,addBrand,formatMessage,invitationUrl,submitEvidence,submitBonus};',ctx);
const a=ctx.a,actor={name:'Ella',role:'admin',agency:'growthcooks'},now='2026-09-01T10:00:00+01:00';
const answers={fullName:'Amara Okafor',email:'amara@example.test',whatsappRaw:'+2348000000001',city:'Ikeja',state:'Lagos',ageConfirmed:true,phoneQuality:'Yes',editingSkills:'Yes',cameraComfort:'Yes',experience:'Regularly',ugcComfort:'Yes',briefComfort:'Comfortable',dailyCapacity:'Yes',availability:'Immediately',introVideo:{name:'demo.mp4',type:'video/mp4',size:1024}};
function setup(){const s=a.createStore();a.apply(s,'growthcooks',answers,'one',now);const p=s.people[0];a.screening(s,actor,p.id,{accepted:true,brand:'CashDrive',tier:'Tier 1'},now);return {s,p};}
let total=0;function test(name,fn){fn();console.log('PASS '+name);total++;}
test('exactly five stage counts with uncontacted visible only in All',()=>{const {s,p}=setup(),v=a.pipelineView(s,actor,'CashDrive');assert.deepEqual(Object.keys(v.counts),['Contacted','Cannot be reached','Unresponsive','Declined','Trial started']);assert.equal(v.total,1);assert.equal(v.people.length,1);assert.equal(a.pipelineStage(p),'');assert.equal(a.pipelineView(s,actor,'CashDrive','','Contacted').people.length,0);});
test('contacted and consent use Contacted until explicit start',()=>{const {s,p}=setup();for(const result of ['CONTACTED_AWAITING_RESPONSE','CREATOR_ACCEPTED_TRIAL']){a.contact(s,actor,p.id,{result,channel:'WhatsApp'},now);assert.equal(a.pipelineStage(p),'Contacted');assert.equal(p.trial,null);}});
test('declined is not rejected or accepted summary and preserves recorder',()=>{const {s,p}=setup();a.contact(s,actor,p.id,{result:'CREATOR_DECLINED',channel:'WhatsApp',reason:'Workload/video volume'},now);assert.equal(a.distributionList(s,actor,'declined')[0].id,p.id);assert.equal(a.distributionList(s,actor,'rejected').length,0);assert.equal(a.distributionList(s,actor,'accepted').length,0);assert.equal(p.contacts[0].actor,'Ella');assert.equal(a.pipelineView(s,actor,'CashDrive','','Declined').people.length,1);assert.equal(a.distributionList(s,{...actor,agency:'other'},'declined').length,0);});
test('rename changes label not immutable person assignment or invitation identity',()=>{const {s,p}=setup(),snapshot=JSON.stringify(p.answers);a.contact(s,actor,p.id,{result:'CREATOR_ACCEPTED_TRIAL',channel:'WhatsApp'},now);assert.ok(a.startTrial(s,actor,p.id,{brand:'CashDrive',tier:'Tier 1',contentType:'Video',start:'2026-09-01'},now).ok);const url=a.invitationUrl(p);assert.ok(a.renameBrand(s,actor,'CashDrive','CashDrive Motors',now).ok);assert.equal(a.brandLabel(s,'CashDrive'),'CashDrive Motors');assert.equal(p.trial.brand,'CashDrive');assert.equal(a.invitationUrl(p),url);assert.equal(JSON.stringify(p.answers),snapshot);assert.match(a.formatMessage(s,p,actor,'outreach'),/Hi Amara,/);assert.match(a.formatMessage(s,p,actor,'outreach'),/CashDrive Motors/);assert.equal(a.pipelineView(s,actor,'CashDrive').total,1);assert.equal(s.settingsEvents.at(-1).before,'CashDrive');});
test('rename collision permission and unsafe key protected',()=>{const {s}=setup();for(const role of ['creator','brand'])assert.equal(a.renameBrand(s,{...actor,role},'CashDrive','Changed',now).ok,false);assert.equal(a.renameBrand(s,{...actor,agency:'other'},'CashDrive','Changed',now).ok,false);for(const name of ['', ' Aura ', '__proto__','constructor'])assert.equal(a.renameBrand(s,actor,'CashDrive',name,now).ok,false);a.renameBrand(s,actor,'CashDrive','Motors',now);assert.equal(a.addBrand(s,actor,' motors ',now).ok,false);assert.equal(a.renameBrand(s,actor,'NorthQuest','CashDrive',now).ok,false);});
test('new trial has no scheduled end but its invitation still expires',()=>{const {s,p}=setup();a.contact(s,actor,p.id,{result:'CREATOR_ACCEPTED_TRIAL',channel:'WhatsApp'},now);assert.ok(a.startTrial(s,actor,p.id,{brand:'CashDrive',tier:'Tier 1',contentType:'Video',start:'2026-09-01'},now).ok);assert.equal(p.trial.due,null);assert.ok(p.invitation.expires>'2026-09-01');const proof={platform:'tiktok',link:'https://www.tiktok.com/@demo/video/123456789',date:'2026-10-01',views:100000,file:{name:'demo.png',type:'image/png',size:100,url:'blob:example'}};assert.ok(a.submitBonus(s,actor,p.id,proof,'2026-10-01T10:00:00+01:00').ok);assert.ok(a.submitEvidence(s,actor,p.id,proof,'2026-10-01T10:00:00+01:00').ok);assert.equal(a.pipelineStage(p),'Trial started');});
test('later internal onboarding states do not add recruitment filters',()=>{for(const state of ['Invited','Completed','Cancelled'])assert.equal(a.pipelineStage({trial:{state:'SUCCESSFUL'},onboarding:{state},outreach:{state:'CREATOR_ACCEPTED_TRIAL'}}),'Trial started');});
console.log(`${total}/${total} simplify checks passed`);
