const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const file=path.join(__dirname,'../prototypes/recruitment.html');
if(!fs.existsSync(file)){console.error('FAIL recruitment prototype has not been built yet');process.exit(1);}
const html=fs.readFileSync(file,'utf8'),ctx=vm.createContext({Date,Intl,URL});
vm.runInContext(html.match(/\/\/ RECRUITMENT CORE START([\s\S]*?)\/\/ RECRUITMENT CORE END/)[1]+';this.api={createStore,normalizePhone,canRead,apply,screening,contact,startTrial,submitEvidence,verify,completeTasks,completeOnboarding,endTrial,cancelOnboarding,addMessage,shareTrial,resolveDuplicate};',ctx);
const a=ctx.api,admin={name:'Ella',role:'admin',agency:'growthcooks'},creator={name:'Amara',role:'creator',agency:'growthcooks',person:'person-1'},other={name:'Other agency',role:'admin',agency:'other'},time='2026-09-06T10:00:00+01:00';
let total=0;function test(name,fn){fn();console.log('PASS '+name);total++;}
const answers={email:'amara@example.test',fullName:'Amara Example',whatsappRaw:'+234 800 000 0001',ageConfirmed:true,city:'Lagos',state:'Lagos',phoneQuality:'Yes',editingSkills:'Yes',cameraComfort:'Sometimes',experience:'Occasionally',ugcComfort:'Yes',briefComfort:'Comfortable',dailyCapacity:'Yes',availability:'Immediately',introVideo:{name:'intro.mp4',type:'video/mp4',size:1024},additionalInfo:''};
function setup(){const s=a.createStore();const r=a.apply(s,'growthcooks',answers,'application-key',time);assert.ok(r.ok);return {s,p:s.people[0]};}
function trial(){const {s,p}=setup();assert.ok(a.screening(s,admin,p.id,{accepted:true,brand:'Aura',tier:'Tier 1',note:''},time).ok);assert.ok(a.contact(s,admin,p.id,{channel:'WhatsApp',result:'CREATOR_ACCEPTED_TRIAL',reason:'',note:''},time).ok);assert.ok(a.startTrial(s,admin,p.id,{brand:'Aura',tier:'Tier 1',contentType:'Video',start:'2026-09-04',due:'2026-09-11',brief:'https://example.test/brief',coach:'Daniel'},time).ok);return {s,p};}
const evidence={platform:'tiktok',link:'https://www.tiktok.com/@demo/video/10001',date:'2026-09-05',views:'10000',file:{name:'proof.png',type:'image/png',size:2048,url:'data:image/png;base64,example'}};
test('raw WhatsApp preserves formatting; normalized number is explicit international',()=>{assert.equal(a.normalizePhone('+234 800-000-0001'),'+2348000000001');assert.equal(a.normalizePhone('08000000001'),null);});
test('application requires core fields and intro video',()=>{const s=a.createStore();assert.equal(a.apply(s,'growthcooks',{...answers,fullName:''},'bad',time).ok,false);assert.equal(s.people.length,0);});
test('application replay is one original snapshot',()=>{const {s,p}=setup();a.apply(s,'growthcooks',answers,'application-key',time);assert.equal(s.people.length,1);assert.ok(Object.isFrozen(p.answers));assert.ok(Object.isFrozen(p.answers.introVideo));});
test('duplicate identity is flagged, not silently merged',()=>{const {s}=setup();a.apply(s,'growthcooks',answers,'different-key',time);assert.equal(s.people.length,2);assert.ok(s.people[1].duplicate);});
test('agency and brand readers cannot see unassigned outsider',()=>{const {p}=setup();assert.equal(a.canRead(other,p),false);assert.equal(a.canRead({role:'brand',agency:'growthcooks',brand:'Aura'},p),false);assert.ok(a.canRead(admin,p));});
test('outreach cannot precede accepted screening',()=>{const {s,p}=setup();assert.equal(a.contact(s,admin,p.id,{channel:'WhatsApp',result:'CONTACTED_AWAITING_RESPONSE'},time).ok,false);});
test('Other rejection requires a note and does not overwrite answers',()=>{const {s,p}=setup(),original=JSON.stringify(p.answers);assert.equal(a.screening(s,admin,p.id,{accepted:false,reason:'Other',note:''},time).ok,false);assert.ok(a.screening(s,admin,p.id,{accepted:false,reason:'Video quality',note:''},time).ok);assert.equal(p.screening.state,'REJECTED_BY_TEAM');assert.equal(JSON.stringify(p.answers),original);assert.equal(p.outreach.state,'NOT_STARTED');});
test('creator decline is separate from team rejection',()=>{const {s,p}=setup();a.screening(s,admin,p.id,{accepted:true,brand:'Aura',tier:'Tier 1'},time);assert.ok(a.contact(s,admin,p.id,{channel:'Phone',result:'CREATOR_DECLINED',reason:'Compensation/pay',note:''},time).ok);assert.equal(p.screening.state,'ACCEPTED_FOR_OUTREACH');assert.equal(p.outreach.reason,'Compensation/pay');assert.equal(p.screening.reason,undefined);});
test('trial requires creator acceptance and all assignment fields',()=>{const {s,p}=setup();assert.equal(a.startTrial(s,admin,p.id,{},time).ok,false);a.screening(s,admin,p.id,{accepted:true,brand:'Aura',tier:'Tier 1'},time);a.contact(s,admin,p.id,{channel:'Phone',result:'CREATOR_ACCEPTED_TRIAL'},time);assert.equal(a.startTrial(s,admin,p.id,{brand:'Aura',start:'2026-09-04'},time).ok,false);});
test('trial uses the original person and agency',()=>{const {p}=trial();assert.equal(p.trial.person,p.person);assert.equal(p.trial.agency,p.agency);});
test('cannot create a second trial or bypass with different agency',()=>{const {s,p}=trial();assert.equal(a.startTrial(s,admin,p.id,p.trial,time).ok,false);assert.equal(a.endTrial(s,other,p.id,'Failed','Reason',time).ok,false);});
test('brand recommendation/assignment alone never grants visibility',()=>{const {s,p}=trial(),brand={role:'brand',agency:'growthcooks',brand:'Aura'};assert.equal(a.canRead(brand,p),false);assert.ok(a.shareTrial(s,admin,p.id,time).ok);assert.ok(a.canRead(brand,p));assert.equal(a.canRead({...brand,brand:'CashDrive'},p),false);});
test('duplicate trial blocked before and after reviewed identity link',()=>{const {s,p}=trial();a.apply(s,'growthcooks',answers,'duplicate-2',time);const otherApp=s.people[1];a.screening(s,admin,otherApp.id,{accepted:true,brand:'CashDrive',tier:'Tier 1'},time);a.contact(s,admin,otherApp.id,{channel:'Phone',result:'CREATOR_ACCEPTED_TRIAL'},time);assert.equal(a.startTrial(s,admin,otherApp.id,p.trial,time).ok,false);assert.ok(a.resolveDuplicate(s,admin,otherApp.id,p.id,'Confirmed same person from both submissions',time).ok);assert.equal(otherApp.person,p.person);assert.equal(a.startTrial(s,admin,otherApp.id,p.trial,time).ok,false);assert.ok(Object.isFrozen(otherApp.answers));});
test('three-record duplicate chain cannot create a new identity',()=>{const {s,p}=setup();a.apply(s,'growthcooks',answers,'second',time);a.apply(s,'growthcooks',answers,'third',time);const b=s.people[1],c=s.people[2];assert.equal(a.resolveDuplicate(s,admin,b.id,c.id,'Matching duplicate',time).ok,false);assert.ok(a.resolveDuplicate(s,admin,c.id,p.id,'Confirmed original',time).ok);assert.ok(a.resolveDuplicate(s,admin,b.id,c.id,'Confirmed reviewed identity',time).ok);assert.equal(b.person,p.person);assert.equal(c.person,p.person);});
test('evidence needs single qualifying link, screenshot and >=10000',()=>{const {s,p}=trial();for(const patch of [{views:'9999'},{file:null},{link:'https://www.tiktok.com/@demo'},{date:'2026-09-01'}])assert.equal(a.submitEvidence(s,creator,p.id,{...evidence,...patch},time).ok,false);assert.equal(p.evidence.length,0);});
test('other creator cannot submit or verify',()=>{const {s,p}=trial();assert.equal(a.submitEvidence(s,{...creator,person:'stranger'},p.id,evidence,time).ok,false);a.submitEvidence(s,creator,p.id,evidence,time);assert.equal(a.verify(s,creator,p.id,{approved:true,checked:true},time).ok,false);});
test('high count alone does not unlock onboarding',()=>{const {s,p}=trial();a.submitEvidence(s,creator,p.id,evidence,time);assert.equal(p.trial.state,'AWAITING_VERIFICATION');assert.equal(p.onboarding,null);assert.ok(Object.isFrozen(p.evidence[0]));});
test('verification requires explicit checked-link-and-image confirmation',()=>{const {s,p}=trial();a.submitEvidence(s,creator,p.id,evidence,time);assert.equal(a.verify(s,admin,p.id,{approved:true,checked:false},time).ok,false);});
test('verified success creates onboarding exactly once and preserves evidence',()=>{const {s,p}=trial();a.submitEvidence(s,creator,p.id,evidence,time);assert.ok(a.verify(s,admin,p.id,{approved:true,checked:true},time).ok);const id=p.onboarding.id,count=s.events.length;assert.ok(a.verify(s,admin,p.id,{approved:true,checked:true},time).ok);assert.equal(p.onboarding.id,id);assert.equal(s.events.length,count);assert.equal(p.evidence.length,1);assert.ok(Object.isFrozen(p.decision));});
test('correction preserves previous snapshot and accepts a new version',()=>{const {s,p}=trial();a.submitEvidence(s,creator,p.id,evidence,time);const original=JSON.stringify(p.evidence[0]);assert.ok(a.verify(s,admin,p.id,{approved:false,note:'Show the visible view count'},time).ok);assert.ok(a.submitEvidence(s,creator,p.id,{...evidence,views:'12000'},time).ok);assert.equal(p.evidence.length,2);assert.equal(JSON.stringify(p.evidence[0]),original);});
test('only completed creator tasks and management confirmation create membership',()=>{const {s,p}=trial();a.submitEvidence(s,creator,p.id,evidence,time);a.verify(s,admin,p.id,{approved:true,checked:true},time);assert.equal(a.completeOnboarding(s,admin,p.id,true,time).ok,false);assert.ok(a.completeTasks(s,creator,p.id,{readBrief:true,profile:'https://www.instagram.com/demo/'},time).ok);assert.ok(a.completeOnboarding(s,admin,p.id,true,time).ok);assert.equal(s.memberships.length,1);a.completeOnboarding(s,admin,p.id,true,time);assert.equal(s.memberships.length,1);assert.equal(s.memberships[0].brand,'Aura');});
test('cancellation cannot grant membership',()=>{const {s,p}=trial();a.submitEvidence(s,creator,p.id,evidence,time);a.verify(s,admin,p.id,{approved:true,checked:true},time);assert.ok(a.cancelOnboarding(s,admin,p.id,'Creator unavailable',time).ok);assert.equal(a.completeOnboarding(s,admin,p.id,true,time).ok,false);assert.equal(s.memberships.length,0);});
test('audit events have scope, actor, time and frozen changes',()=>{const {s}=trial();for(const e of s.events){assert.equal(e.agency,'growthcooks');assert.ok(e.actor&&e.role&&e.at&&e.action&&e.source);assert.ok(Object.isFrozen(e));}});
test('no external mutation or persistence in prototype',()=>assert.doesNotMatch(html,/fetch\(|XMLHttpRequest|localStorage|sessionStorage|supabase\.co/));
console.log(`${total}/${total} recruitment checks passed`);
